// Code generated by go-swagger; DO NOT EDIT.

package monitoring

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRuleParams creates a new GetRuleParams object
// with the default values initialized.
func NewGetRuleParams() *GetRuleParams {
	var ()
	return &GetRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRuleParamsWithTimeout creates a new GetRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRuleParamsWithTimeout(timeout time.Duration) *GetRuleParams {
	var ()
	return &GetRuleParams{

		timeout: timeout,
	}
}

// NewGetRuleParamsWithContext creates a new GetRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRuleParamsWithContext(ctx context.Context) *GetRuleParams {
	var ()
	return &GetRuleParams{

		Context: ctx,
	}
}

// NewGetRuleParamsWithHTTPClient creates a new GetRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRuleParamsWithHTTPClient(client *http.Client) *GetRuleParams {
	var ()
	return &GetRuleParams{
		HTTPClient: client,
	}
}

/*GetRuleParams contains all the parameters to send to the API endpoint
for the get rule operation typically these are written to a http.Request
*/
type GetRuleParams struct {

	/*Group
	  Is the group of the kind

	*/
	Group string
	/*Kind
	  Is the kind of the resource

	*/
	Kind string
	/*Name
	  Is the name of the alerting rule

	*/
	Name string
	/*Namespace
	  Is the namespace of the resource

	*/
	Namespace string
	/*Resource
	  Is the name of the resource

	*/
	Resource string
	/*Version
	  Is the version of the kind

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get rule params
func (o *GetRuleParams) WithTimeout(timeout time.Duration) *GetRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get rule params
func (o *GetRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get rule params
func (o *GetRuleParams) WithContext(ctx context.Context) *GetRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get rule params
func (o *GetRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get rule params
func (o *GetRuleParams) WithHTTPClient(client *http.Client) *GetRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get rule params
func (o *GetRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroup adds the group to the get rule params
func (o *GetRuleParams) WithGroup(group string) *GetRuleParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the get rule params
func (o *GetRuleParams) SetGroup(group string) {
	o.Group = group
}

// WithKind adds the kind to the get rule params
func (o *GetRuleParams) WithKind(kind string) *GetRuleParams {
	o.SetKind(kind)
	return o
}

// SetKind adds the kind to the get rule params
func (o *GetRuleParams) SetKind(kind string) {
	o.Kind = kind
}

// WithName adds the name to the get rule params
func (o *GetRuleParams) WithName(name string) *GetRuleParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get rule params
func (o *GetRuleParams) SetName(name string) {
	o.Name = name
}

// WithNamespace adds the namespace to the get rule params
func (o *GetRuleParams) WithNamespace(namespace string) *GetRuleParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get rule params
func (o *GetRuleParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithResource adds the resource to the get rule params
func (o *GetRuleParams) WithResource(resource string) *GetRuleParams {
	o.SetResource(resource)
	return o
}

// SetResource adds the resource to the get rule params
func (o *GetRuleParams) SetResource(resource string) {
	o.Resource = resource
}

// WithVersion adds the version to the get rule params
func (o *GetRuleParams) WithVersion(version string) *GetRuleParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get rule params
func (o *GetRuleParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group
	if err := r.SetPathParam("group", o.Group); err != nil {
		return err
	}

	// path param kind
	if err := r.SetPathParam("kind", o.Kind); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param resource
	if err := r.SetPathParam("resource", o.Resource); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
