// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteEKSNodeGroupsParams creates a new DeleteEKSNodeGroupsParams object
// with the default values initialized.
func NewDeleteEKSNodeGroupsParams() *DeleteEKSNodeGroupsParams {
	var ()
	return &DeleteEKSNodeGroupsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEKSNodeGroupsParamsWithTimeout creates a new DeleteEKSNodeGroupsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteEKSNodeGroupsParamsWithTimeout(timeout time.Duration) *DeleteEKSNodeGroupsParams {
	var ()
	return &DeleteEKSNodeGroupsParams{

		timeout: timeout,
	}
}

// NewDeleteEKSNodeGroupsParamsWithContext creates a new DeleteEKSNodeGroupsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteEKSNodeGroupsParamsWithContext(ctx context.Context) *DeleteEKSNodeGroupsParams {
	var ()
	return &DeleteEKSNodeGroupsParams{

		Context: ctx,
	}
}

// NewDeleteEKSNodeGroupsParamsWithHTTPClient creates a new DeleteEKSNodeGroupsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteEKSNodeGroupsParamsWithHTTPClient(client *http.Client) *DeleteEKSNodeGroupsParams {
	var ()
	return &DeleteEKSNodeGroupsParams{
		HTTPClient: client,
	}
}

/*DeleteEKSNodeGroupsParams contains all the parameters to send to the API endpoint
for the delete e k s node groups operation typically these are written to a http.Request
*/
type DeleteEKSNodeGroupsParams struct {

	/*Name
	  Is the name of the EKS nodegroup

	*/
	Name string
	/*Team
	  Is the name of the team you are acting within

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete e k s node groups params
func (o *DeleteEKSNodeGroupsParams) WithTimeout(timeout time.Duration) *DeleteEKSNodeGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete e k s node groups params
func (o *DeleteEKSNodeGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete e k s node groups params
func (o *DeleteEKSNodeGroupsParams) WithContext(ctx context.Context) *DeleteEKSNodeGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete e k s node groups params
func (o *DeleteEKSNodeGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete e k s node groups params
func (o *DeleteEKSNodeGroupsParams) WithHTTPClient(client *http.Client) *DeleteEKSNodeGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete e k s node groups params
func (o *DeleteEKSNodeGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete e k s node groups params
func (o *DeleteEKSNodeGroupsParams) WithName(name string) *DeleteEKSNodeGroupsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete e k s node groups params
func (o *DeleteEKSNodeGroupsParams) SetName(name string) {
	o.Name = name
}

// WithTeam adds the team to the delete e k s node groups params
func (o *DeleteEKSNodeGroupsParams) WithTeam(team string) *DeleteEKSNodeGroupsParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the delete e k s node groups params
func (o *DeleteEKSNodeGroupsParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEKSNodeGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
