// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// DeleteProjectClaimReader is a Reader for the DeleteProjectClaim structure.
type DeleteProjectClaimReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProjectClaimReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteProjectClaimOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteProjectClaimDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteProjectClaimOK creates a DeleteProjectClaimOK with default headers values
func NewDeleteProjectClaimOK() *DeleteProjectClaimOK {
	return &DeleteProjectClaimOK{}
}

/*DeleteProjectClaimOK handles this case with default header values.

Contains the former team definition from the kore
*/
type DeleteProjectClaimOK struct {
	Payload *models.V1alpha1ProjectClaim
}

func (o *DeleteProjectClaimOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1alpha1/teams/{team}/projectclaims/{name}][%d] deleteProjectClaimOK  %+v", 200, o.Payload)
}

func (o *DeleteProjectClaimOK) GetPayload() *models.V1alpha1ProjectClaim {
	return o.Payload
}

func (o *DeleteProjectClaimOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1ProjectClaim)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProjectClaimDefault creates a DeleteProjectClaimDefault with default headers values
func NewDeleteProjectClaimDefault(code int) *DeleteProjectClaimDefault {
	return &DeleteProjectClaimDefault{
		_statusCode: code,
	}
}

/*DeleteProjectClaimDefault handles this case with default header values.

A generic API error containing the cause of the error
*/
type DeleteProjectClaimDefault struct {
	_statusCode int

	Payload *models.ApiserverError
}

// Code gets the status code for the delete project claim default response
func (o *DeleteProjectClaimDefault) Code() int {
	return o._statusCode
}

func (o *DeleteProjectClaimDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1alpha1/teams/{team}/projectclaims/{name}][%d] deleteProjectClaim default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteProjectClaimDefault) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *DeleteProjectClaimDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
