// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// FindOrganizationReader is a Reader for the FindOrganization structure.
type FindOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFindOrganizationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFindOrganizationOK creates a FindOrganizationOK with default headers values
func NewFindOrganizationOK() *FindOrganizationOK {
	return &FindOrganizationOK{}
}

/*FindOrganizationOK handles this case with default header values.

Contains the former team definition from the kore
*/
type FindOrganizationOK struct {
	Payload *models.V1alpha1Organization
}

func (o *FindOrganizationOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/organizations/{name}][%d] findOrganizationOK  %+v", 200, o.Payload)
}

func (o *FindOrganizationOK) GetPayload() *models.V1alpha1Organization {
	return o.Payload
}

func (o *FindOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Organization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindOrganizationDefault creates a FindOrganizationDefault with default headers values
func NewFindOrganizationDefault(code int) *FindOrganizationDefault {
	return &FindOrganizationDefault{
		_statusCode: code,
	}
}

/*FindOrganizationDefault handles this case with default header values.

A generic API error containing the cause of the error
*/
type FindOrganizationDefault struct {
	_statusCode int

	Payload *models.ApiserverError
}

// Code gets the status code for the find organization default response
func (o *FindOrganizationDefault) Code() int {
	return o._statusCode
}

func (o *FindOrganizationDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/organizations/{name}][%d] findOrganization default  %+v", o._statusCode, o.Payload)
}

func (o *FindOrganizationDefault) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *FindOrganizationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
