// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// FindAWSAccountClaimsReader is a Reader for the FindAWSAccountClaims structure.
type FindAWSAccountClaimsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindAWSAccountClaimsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindAWSAccountClaimsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFindAWSAccountClaimsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFindAWSAccountClaimsOK creates a FindAWSAccountClaimsOK with default headers values
func NewFindAWSAccountClaimsOK() *FindAWSAccountClaimsOK {
	return &FindAWSAccountClaimsOK{}
}

/*FindAWSAccountClaimsOK handles this case with default header values.

Contains the former team definition from the kore
*/
type FindAWSAccountClaimsOK struct {
	Payload *models.V1alpha1AWSAccountClaimList
}

func (o *FindAWSAccountClaimsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/awsaccountclaims][%d] findAWSAccountClaimsOK  %+v", 200, o.Payload)
}

func (o *FindAWSAccountClaimsOK) GetPayload() *models.V1alpha1AWSAccountClaimList {
	return o.Payload
}

func (o *FindAWSAccountClaimsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1AWSAccountClaimList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindAWSAccountClaimsDefault creates a FindAWSAccountClaimsDefault with default headers values
func NewFindAWSAccountClaimsDefault(code int) *FindAWSAccountClaimsDefault {
	return &FindAWSAccountClaimsDefault{
		_statusCode: code,
	}
}

/*FindAWSAccountClaimsDefault handles this case with default header values.

A generic API error containing the cause of the error
*/
type FindAWSAccountClaimsDefault struct {
	_statusCode int

	Payload *models.ApiserverError
}

// Code gets the status code for the find a w s account claims default response
func (o *FindAWSAccountClaimsDefault) Code() int {
	return o._statusCode
}

func (o *FindAWSAccountClaimsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/awsaccountclaims][%d] findAWSAccountClaims default  %+v", o._statusCode, o.Payload)
}

func (o *FindAWSAccountClaimsDefault) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *FindAWSAccountClaimsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
