// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// FindAWSAccountClaimReader is a Reader for the FindAWSAccountClaim structure.
type FindAWSAccountClaimReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindAWSAccountClaimReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindAWSAccountClaimOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFindAWSAccountClaimDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFindAWSAccountClaimOK creates a FindAWSAccountClaimOK with default headers values
func NewFindAWSAccountClaimOK() *FindAWSAccountClaimOK {
	return &FindAWSAccountClaimOK{}
}

/*FindAWSAccountClaimOK handles this case with default header values.

Contains the former team definition from the kore
*/
type FindAWSAccountClaimOK struct {
	Payload *models.V1alpha1AWSAccountClaim
}

func (o *FindAWSAccountClaimOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/awsaccountclaims/{name}][%d] findAWSAccountClaimOK  %+v", 200, o.Payload)
}

func (o *FindAWSAccountClaimOK) GetPayload() *models.V1alpha1AWSAccountClaim {
	return o.Payload
}

func (o *FindAWSAccountClaimOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1AWSAccountClaim)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindAWSAccountClaimDefault creates a FindAWSAccountClaimDefault with default headers values
func NewFindAWSAccountClaimDefault(code int) *FindAWSAccountClaimDefault {
	return &FindAWSAccountClaimDefault{
		_statusCode: code,
	}
}

/*FindAWSAccountClaimDefault handles this case with default header values.

A generic API error containing the cause of the error
*/
type FindAWSAccountClaimDefault struct {
	_statusCode int

	Payload *models.ApiserverError
}

// Code gets the status code for the find a w s account claim default response
func (o *FindAWSAccountClaimDefault) Code() int {
	return o._statusCode
}

func (o *FindAWSAccountClaimDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/awsaccountclaims/{name}][%d] findAWSAccountClaim default  %+v", o._statusCode, o.Payload)
}

func (o *FindAWSAccountClaimDefault) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *FindAWSAccountClaimDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
