// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindOrganizationParams creates a new FindOrganizationParams object
// with the default values initialized.
func NewFindOrganizationParams() *FindOrganizationParams {
	var ()
	return &FindOrganizationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindOrganizationParamsWithTimeout creates a new FindOrganizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindOrganizationParamsWithTimeout(timeout time.Duration) *FindOrganizationParams {
	var ()
	return &FindOrganizationParams{

		timeout: timeout,
	}
}

// NewFindOrganizationParamsWithContext creates a new FindOrganizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindOrganizationParamsWithContext(ctx context.Context) *FindOrganizationParams {
	var ()
	return &FindOrganizationParams{

		Context: ctx,
	}
}

// NewFindOrganizationParamsWithHTTPClient creates a new FindOrganizationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindOrganizationParamsWithHTTPClient(client *http.Client) *FindOrganizationParams {
	var ()
	return &FindOrganizationParams{
		HTTPClient: client,
	}
}

/*FindOrganizationParams contains all the parameters to send to the API endpoint
for the find organization operation typically these are written to a http.Request
*/
type FindOrganizationParams struct {

	/*Name
	  Is name the of the resource you are acting on

	*/
	Name string
	/*Team
	  Is the name of the team you are acting within

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find organization params
func (o *FindOrganizationParams) WithTimeout(timeout time.Duration) *FindOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find organization params
func (o *FindOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find organization params
func (o *FindOrganizationParams) WithContext(ctx context.Context) *FindOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find organization params
func (o *FindOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find organization params
func (o *FindOrganizationParams) WithHTTPClient(client *http.Client) *FindOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find organization params
func (o *FindOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the find organization params
func (o *FindOrganizationParams) WithName(name string) *FindOrganizationParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the find organization params
func (o *FindOrganizationParams) SetName(name string) {
	o.Name = name
}

// WithTeam adds the team to the find organization params
func (o *FindOrganizationParams) WithTeam(team string) *FindOrganizationParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the find organization params
func (o *FindOrganizationParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *FindOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
