// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// FindProjectClaimReader is a Reader for the FindProjectClaim structure.
type FindProjectClaimReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindProjectClaimReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindProjectClaimOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFindProjectClaimDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFindProjectClaimOK creates a FindProjectClaimOK with default headers values
func NewFindProjectClaimOK() *FindProjectClaimOK {
	return &FindProjectClaimOK{}
}

/*FindProjectClaimOK handles this case with default header values.

Contains the former team definition from the kore
*/
type FindProjectClaimOK struct {
	Payload *models.V1alpha1ProjectClaim
}

func (o *FindProjectClaimOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/projectclaims/{name}][%d] findProjectClaimOK  %+v", 200, o.Payload)
}

func (o *FindProjectClaimOK) GetPayload() *models.V1alpha1ProjectClaim {
	return o.Payload
}

func (o *FindProjectClaimOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1ProjectClaim)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindProjectClaimDefault creates a FindProjectClaimDefault with default headers values
func NewFindProjectClaimDefault(code int) *FindProjectClaimDefault {
	return &FindProjectClaimDefault{
		_statusCode: code,
	}
}

/*FindProjectClaimDefault handles this case with default header values.

A generic API error containing the cause of the error
*/
type FindProjectClaimDefault struct {
	_statusCode int

	Payload *models.ApiserverError
}

// Code gets the status code for the find project claim default response
func (o *FindProjectClaimDefault) Code() int {
	return o._statusCode
}

func (o *FindProjectClaimDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/projectclaims/{name}][%d] findProjectClaim default  %+v", o._statusCode, o.Payload)
}

func (o *FindProjectClaimDefault) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *FindProjectClaimDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
