// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTeamSecretParams creates a new GetTeamSecretParams object
// with the default values initialized.
func NewGetTeamSecretParams() *GetTeamSecretParams {
	var ()
	return &GetTeamSecretParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTeamSecretParamsWithTimeout creates a new GetTeamSecretParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTeamSecretParamsWithTimeout(timeout time.Duration) *GetTeamSecretParams {
	var ()
	return &GetTeamSecretParams{

		timeout: timeout,
	}
}

// NewGetTeamSecretParamsWithContext creates a new GetTeamSecretParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTeamSecretParamsWithContext(ctx context.Context) *GetTeamSecretParams {
	var ()
	return &GetTeamSecretParams{

		Context: ctx,
	}
}

// NewGetTeamSecretParamsWithHTTPClient creates a new GetTeamSecretParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTeamSecretParamsWithHTTPClient(client *http.Client) *GetTeamSecretParams {
	var ()
	return &GetTeamSecretParams{
		HTTPClient: client,
	}
}

/*GetTeamSecretParams contains all the parameters to send to the API endpoint
for the get team secret operation typically these are written to a http.Request
*/
type GetTeamSecretParams struct {

	/*Name
	  Is name the of the secert in the name

	*/
	Name string
	/*Team
	  Is the name of the team you are acting within

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get team secret params
func (o *GetTeamSecretParams) WithTimeout(timeout time.Duration) *GetTeamSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get team secret params
func (o *GetTeamSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get team secret params
func (o *GetTeamSecretParams) WithContext(ctx context.Context) *GetTeamSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get team secret params
func (o *GetTeamSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get team secret params
func (o *GetTeamSecretParams) WithHTTPClient(client *http.Client) *GetTeamSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get team secret params
func (o *GetTeamSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get team secret params
func (o *GetTeamSecretParams) WithName(name string) *GetTeamSecretParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get team secret params
func (o *GetTeamSecretParams) SetName(name string) {
	o.Name = name
}

// WithTeam adds the team to the get team secret params
func (o *GetTeamSecretParams) WithTeam(team string) *GetTeamSecretParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the get team secret params
func (o *GetTeamSecretParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *GetTeamSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
