// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetKubernetesParams creates a new GetKubernetesParams object
// with the default values initialized.
func NewGetKubernetesParams() *GetKubernetesParams {
	var ()
	return &GetKubernetesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetKubernetesParamsWithTimeout creates a new GetKubernetesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetKubernetesParamsWithTimeout(timeout time.Duration) *GetKubernetesParams {
	var ()
	return &GetKubernetesParams{

		timeout: timeout,
	}
}

// NewGetKubernetesParamsWithContext creates a new GetKubernetesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetKubernetesParamsWithContext(ctx context.Context) *GetKubernetesParams {
	var ()
	return &GetKubernetesParams{

		Context: ctx,
	}
}

// NewGetKubernetesParamsWithHTTPClient creates a new GetKubernetesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetKubernetesParamsWithHTTPClient(client *http.Client) *GetKubernetesParams {
	var ()
	return &GetKubernetesParams{
		HTTPClient: client,
	}
}

/*GetKubernetesParams contains all the parameters to send to the API endpoint
for the get kubernetes operation typically these are written to a http.Request
*/
type GetKubernetesParams struct {

	/*Name
	  Is name the of the kubernetes object you are acting upon

	*/
	Name string
	/*Team
	  Is the name of the team you are acting within

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get kubernetes params
func (o *GetKubernetesParams) WithTimeout(timeout time.Duration) *GetKubernetesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get kubernetes params
func (o *GetKubernetesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get kubernetes params
func (o *GetKubernetesParams) WithContext(ctx context.Context) *GetKubernetesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get kubernetes params
func (o *GetKubernetesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get kubernetes params
func (o *GetKubernetesParams) WithHTTPClient(client *http.Client) *GetKubernetesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get kubernetes params
func (o *GetKubernetesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get kubernetes params
func (o *GetKubernetesParams) WithName(name string) *GetKubernetesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get kubernetes params
func (o *GetKubernetesParams) SetName(name string) {
	o.Name = name
}

// WithTeam adds the team to the get kubernetes params
func (o *GetKubernetesParams) WithTeam(team string) *GetKubernetesParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the get kubernetes params
func (o *GetKubernetesParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *GetKubernetesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
