// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetServiceCredentialSchemaForKindParams creates a new GetServiceCredentialSchemaForKindParams object
// with the default values initialized.
func NewGetServiceCredentialSchemaForKindParams() *GetServiceCredentialSchemaForKindParams {
	var ()
	return &GetServiceCredentialSchemaForKindParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServiceCredentialSchemaForKindParamsWithTimeout creates a new GetServiceCredentialSchemaForKindParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServiceCredentialSchemaForKindParamsWithTimeout(timeout time.Duration) *GetServiceCredentialSchemaForKindParams {
	var ()
	return &GetServiceCredentialSchemaForKindParams{

		timeout: timeout,
	}
}

// NewGetServiceCredentialSchemaForKindParamsWithContext creates a new GetServiceCredentialSchemaForKindParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServiceCredentialSchemaForKindParamsWithContext(ctx context.Context) *GetServiceCredentialSchemaForKindParams {
	var ()
	return &GetServiceCredentialSchemaForKindParams{

		Context: ctx,
	}
}

// NewGetServiceCredentialSchemaForKindParamsWithHTTPClient creates a new GetServiceCredentialSchemaForKindParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServiceCredentialSchemaForKindParamsWithHTTPClient(client *http.Client) *GetServiceCredentialSchemaForKindParams {
	var ()
	return &GetServiceCredentialSchemaForKindParams{
		HTTPClient: client,
	}
}

/*GetServiceCredentialSchemaForKindParams contains all the parameters to send to the API endpoint
for the get service credential schema for kind operation typically these are written to a http.Request
*/
type GetServiceCredentialSchemaForKindParams struct {

	/*Kind
	  The service kind

	*/
	Kind string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get service credential schema for kind params
func (o *GetServiceCredentialSchemaForKindParams) WithTimeout(timeout time.Duration) *GetServiceCredentialSchemaForKindParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service credential schema for kind params
func (o *GetServiceCredentialSchemaForKindParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service credential schema for kind params
func (o *GetServiceCredentialSchemaForKindParams) WithContext(ctx context.Context) *GetServiceCredentialSchemaForKindParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service credential schema for kind params
func (o *GetServiceCredentialSchemaForKindParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get service credential schema for kind params
func (o *GetServiceCredentialSchemaForKindParams) WithHTTPClient(client *http.Client) *GetServiceCredentialSchemaForKindParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get service credential schema for kind params
func (o *GetServiceCredentialSchemaForKindParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKind adds the kind to the get service credential schema for kind params
func (o *GetServiceCredentialSchemaForKindParams) WithKind(kind string) *GetServiceCredentialSchemaForKindParams {
	o.SetKind(kind)
	return o
}

// SetKind adds the kind to the get service credential schema for kind params
func (o *GetServiceCredentialSchemaForKindParams) SetKind(kind string) {
	o.Kind = kind
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceCredentialSchemaForKindParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param kind
	if err := r.SetPathParam("kind", o.Kind); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
