// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTeamAuditParams creates a new GetTeamAuditParams object
// with the default values initialized.
func NewGetTeamAuditParams() *GetTeamAuditParams {
	var (
		sinceDefault = string("60m")
	)
	return &GetTeamAuditParams{
		Since: &sinceDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTeamAuditParamsWithTimeout creates a new GetTeamAuditParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTeamAuditParamsWithTimeout(timeout time.Duration) *GetTeamAuditParams {
	var (
		sinceDefault = string("60m")
	)
	return &GetTeamAuditParams{
		Since: &sinceDefault,

		timeout: timeout,
	}
}

// NewGetTeamAuditParamsWithContext creates a new GetTeamAuditParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTeamAuditParamsWithContext(ctx context.Context) *GetTeamAuditParams {
	var (
		sinceDefault = string("60m")
	)
	return &GetTeamAuditParams{
		Since: &sinceDefault,

		Context: ctx,
	}
}

// NewGetTeamAuditParamsWithHTTPClient creates a new GetTeamAuditParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTeamAuditParamsWithHTTPClient(client *http.Client) *GetTeamAuditParams {
	var (
		sinceDefault = string("60m")
	)
	return &GetTeamAuditParams{
		Since:      &sinceDefault,
		HTTPClient: client,
	}
}

/*GetTeamAuditParams contains all the parameters to send to the API endpoint
for the get team audit operation typically these are written to a http.Request
*/
type GetTeamAuditParams struct {

	/*Since
	  The duration to retrieve from the audit log

	*/
	Since *string
	/*Team
	  Is the name of the team you are acting within

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get team audit params
func (o *GetTeamAuditParams) WithTimeout(timeout time.Duration) *GetTeamAuditParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get team audit params
func (o *GetTeamAuditParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get team audit params
func (o *GetTeamAuditParams) WithContext(ctx context.Context) *GetTeamAuditParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get team audit params
func (o *GetTeamAuditParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get team audit params
func (o *GetTeamAuditParams) WithHTTPClient(client *http.Client) *GetTeamAuditParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get team audit params
func (o *GetTeamAuditParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSince adds the since to the get team audit params
func (o *GetTeamAuditParams) WithSince(since *string) *GetTeamAuditParams {
	o.SetSince(since)
	return o
}

// SetSince adds the since to the get team audit params
func (o *GetTeamAuditParams) SetSince(since *string) {
	o.Since = since
}

// WithTeam adds the team to the get team audit params
func (o *GetTeamAuditParams) WithTeam(team string) *GetTeamAuditParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the get team audit params
func (o *GetTeamAuditParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *GetTeamAuditParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Since != nil {

		// query param since
		var qrSince string
		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := qrSince
		if qSince != "" {
			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}

	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
