// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// GetPlanReader is a Reader for the GetPlan structure.
type GetPlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetPlanDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPlanOK creates a GetPlanOK with default headers values
func NewGetPlanOK() *GetPlanOK {
	return &GetPlanOK{}
}

/*GetPlanOK handles this case with default header values.

Contains the class definition from the kore
*/
type GetPlanOK struct {
	Payload *models.V1Plan
}

func (o *GetPlanOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/plans/{name}][%d] getPlanOK  %+v", 200, o.Payload)
}

func (o *GetPlanOK) GetPayload() *models.V1Plan {
	return o.Payload
}

func (o *GetPlanOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1Plan)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPlanDefault creates a GetPlanDefault with default headers values
func NewGetPlanDefault(code int) *GetPlanDefault {
	return &GetPlanDefault{
		_statusCode: code,
	}
}

/*GetPlanDefault handles this case with default header values.

A generic API error containing the cause of the error
*/
type GetPlanDefault struct {
	_statusCode int

	Payload *models.ApiserverError
}

// Code gets the status code for the get plan default response
func (o *GetPlanDefault) Code() int {
	return o._statusCode
}

func (o *GetPlanDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/plans/{name}][%d] GetPlan default  %+v", o._statusCode, o.Payload)
}

func (o *GetPlanDefault) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *GetPlanDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
