// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetServiceKindParams creates a new GetServiceKindParams object
// with the default values initialized.
func NewGetServiceKindParams() *GetServiceKindParams {
	var ()
	return &GetServiceKindParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServiceKindParamsWithTimeout creates a new GetServiceKindParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServiceKindParamsWithTimeout(timeout time.Duration) *GetServiceKindParams {
	var ()
	return &GetServiceKindParams{

		timeout: timeout,
	}
}

// NewGetServiceKindParamsWithContext creates a new GetServiceKindParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServiceKindParamsWithContext(ctx context.Context) *GetServiceKindParams {
	var ()
	return &GetServiceKindParams{

		Context: ctx,
	}
}

// NewGetServiceKindParamsWithHTTPClient creates a new GetServiceKindParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetServiceKindParamsWithHTTPClient(client *http.Client) *GetServiceKindParams {
	var ()
	return &GetServiceKindParams{
		HTTPClient: client,
	}
}

/*GetServiceKindParams contains all the parameters to send to the API endpoint
for the get service kind operation typically these are written to a http.Request
*/
type GetServiceKindParams struct {

	/*Name
	  The name of the service kind you wish to retrieve

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get service kind params
func (o *GetServiceKindParams) WithTimeout(timeout time.Duration) *GetServiceKindParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service kind params
func (o *GetServiceKindParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service kind params
func (o *GetServiceKindParams) WithContext(ctx context.Context) *GetServiceKindParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service kind params
func (o *GetServiceKindParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get service kind params
func (o *GetServiceKindParams) WithHTTPClient(client *http.Client) *GetServiceKindParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get service kind params
func (o *GetServiceKindParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get service kind params
func (o *GetServiceKindParams) WithName(name string) *GetServiceKindParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get service kind params
func (o *GetServiceKindParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceKindParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
