// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// GetServiceCredentialSchemaForKindReader is a Reader for the GetServiceCredentialSchemaForKind structure.
type GetServiceCredentialSchemaForKindReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServiceCredentialSchemaForKindReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServiceCredentialSchemaForKindOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetServiceCredentialSchemaForKindUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetServiceCredentialSchemaForKindForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetServiceCredentialSchemaForKindInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetServiceCredentialSchemaForKindOK creates a GetServiceCredentialSchemaForKindOK with default headers values
func NewGetServiceCredentialSchemaForKindOK() *GetServiceCredentialSchemaForKindOK {
	return &GetServiceCredentialSchemaForKindOK{}
}

/*GetServiceCredentialSchemaForKindOK handles this case with default header values.

Contains the service credential schema definition
*/
type GetServiceCredentialSchemaForKindOK struct {
}

func (o *GetServiceCredentialSchemaForKindOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/servicecredentialschemas/{kind}][%d] getServiceCredentialSchemaForKindOK ", 200)
}

func (o *GetServiceCredentialSchemaForKindOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServiceCredentialSchemaForKindUnauthorized creates a GetServiceCredentialSchemaForKindUnauthorized with default headers values
func NewGetServiceCredentialSchemaForKindUnauthorized() *GetServiceCredentialSchemaForKindUnauthorized {
	return &GetServiceCredentialSchemaForKindUnauthorized{}
}

/*GetServiceCredentialSchemaForKindUnauthorized handles this case with default header values.

If not authenticated
*/
type GetServiceCredentialSchemaForKindUnauthorized struct {
}

func (o *GetServiceCredentialSchemaForKindUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/servicecredentialschemas/{kind}][%d] getServiceCredentialSchemaForKindUnauthorized ", 401)
}

func (o *GetServiceCredentialSchemaForKindUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServiceCredentialSchemaForKindForbidden creates a GetServiceCredentialSchemaForKindForbidden with default headers values
func NewGetServiceCredentialSchemaForKindForbidden() *GetServiceCredentialSchemaForKindForbidden {
	return &GetServiceCredentialSchemaForKindForbidden{}
}

/*GetServiceCredentialSchemaForKindForbidden handles this case with default header values.

If authenticated but not authorized
*/
type GetServiceCredentialSchemaForKindForbidden struct {
}

func (o *GetServiceCredentialSchemaForKindForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/servicecredentialschemas/{kind}][%d] getServiceCredentialSchemaForKindForbidden ", 403)
}

func (o *GetServiceCredentialSchemaForKindForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServiceCredentialSchemaForKindInternalServerError creates a GetServiceCredentialSchemaForKindInternalServerError with default headers values
func NewGetServiceCredentialSchemaForKindInternalServerError() *GetServiceCredentialSchemaForKindInternalServerError {
	return &GetServiceCredentialSchemaForKindInternalServerError{}
}

/*GetServiceCredentialSchemaForKindInternalServerError handles this case with default header values.

A generic API error containing the cause of the error
*/
type GetServiceCredentialSchemaForKindInternalServerError struct {
	Payload *models.ApiserverError
}

func (o *GetServiceCredentialSchemaForKindInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/servicecredentialschemas/{kind}][%d] getServiceCredentialSchemaForKindInternalServerError  %+v", 500, o.Payload)
}

func (o *GetServiceCredentialSchemaForKindInternalServerError) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *GetServiceCredentialSchemaForKindInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
