// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// ListEKSCredentialsReader is a Reader for the ListEKSCredentials structure.
type ListEKSCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListEKSCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListEKSCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListEKSCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListEKSCredentialsOK creates a ListEKSCredentialsOK with default headers values
func NewListEKSCredentialsOK() *ListEKSCredentialsOK {
	return &ListEKSCredentialsOK{}
}

/*ListEKSCredentialsOK handles this case with default header values.

Contains the former team definition from the kore
*/
type ListEKSCredentialsOK struct {
	Payload *models.V1alpha1EKSCredentialsList
}

func (o *ListEKSCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/ekscredentials][%d] listEKSCredentialsOK  %+v", 200, o.Payload)
}

func (o *ListEKSCredentialsOK) GetPayload() *models.V1alpha1EKSCredentialsList {
	return o.Payload
}

func (o *ListEKSCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1EKSCredentialsList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEKSCredentialsDefault creates a ListEKSCredentialsDefault with default headers values
func NewListEKSCredentialsDefault(code int) *ListEKSCredentialsDefault {
	return &ListEKSCredentialsDefault{
		_statusCode: code,
	}
}

/*ListEKSCredentialsDefault handles this case with default header values.

A generic API error containing the cause of the error
*/
type ListEKSCredentialsDefault struct {
	_statusCode int

	Payload *models.ApiserverError
}

// Code gets the status code for the list e k s credentials default response
func (o *ListEKSCredentialsDefault) Code() int {
	return o._statusCode
}

func (o *ListEKSCredentialsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/ekscredentials][%d] ListEKSCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *ListEKSCredentialsDefault) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *ListEKSCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
