// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// ListServicePLansReader is a Reader for the ListServicePLans structure.
type ListServicePLansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListServicePLansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListServicePLansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListServicePLansUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListServicePLansForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListServicePLansInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListServicePLansOK creates a ListServicePLansOK with default headers values
func NewListServicePLansOK() *ListServicePLansOK {
	return &ListServicePLansOK{}
}

/*ListServicePLansOK handles this case with default header values.

A list of service plans
*/
type ListServicePLansOK struct {
	Payload *models.V1ServicePlanList
}

func (o *ListServicePLansOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/serviceplans][%d] listServicePLansOK  %+v", 200, o.Payload)
}

func (o *ListServicePLansOK) GetPayload() *models.V1ServicePlanList {
	return o.Payload
}

func (o *ListServicePLansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ServicePlanList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListServicePLansUnauthorized creates a ListServicePLansUnauthorized with default headers values
func NewListServicePLansUnauthorized() *ListServicePLansUnauthorized {
	return &ListServicePLansUnauthorized{}
}

/*ListServicePLansUnauthorized handles this case with default header values.

If not authenticated
*/
type ListServicePLansUnauthorized struct {
}

func (o *ListServicePLansUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/serviceplans][%d] listServicePLansUnauthorized ", 401)
}

func (o *ListServicePLansUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListServicePLansForbidden creates a ListServicePLansForbidden with default headers values
func NewListServicePLansForbidden() *ListServicePLansForbidden {
	return &ListServicePLansForbidden{}
}

/*ListServicePLansForbidden handles this case with default header values.

If authenticated but not authorized
*/
type ListServicePLansForbidden struct {
}

func (o *ListServicePLansForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/serviceplans][%d] listServicePLansForbidden ", 403)
}

func (o *ListServicePLansForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListServicePLansInternalServerError creates a ListServicePLansInternalServerError with default headers values
func NewListServicePLansInternalServerError() *ListServicePLansInternalServerError {
	return &ListServicePLansInternalServerError{}
}

/*ListServicePLansInternalServerError handles this case with default header values.

A generic API error containing the cause of the error
*/
type ListServicePLansInternalServerError struct {
	Payload *models.ApiserverError
}

func (o *ListServicePLansInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/serviceplans][%d] listServicePLansInternalServerError  %+v", 500, o.Payload)
}

func (o *ListServicePLansInternalServerError) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *ListServicePLansInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
