// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListSecurityScansForResourceParams creates a new ListSecurityScansForResourceParams object
// with the default values initialized.
func NewListSecurityScansForResourceParams() *ListSecurityScansForResourceParams {
	var ()
	return &ListSecurityScansForResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListSecurityScansForResourceParamsWithTimeout creates a new ListSecurityScansForResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListSecurityScansForResourceParamsWithTimeout(timeout time.Duration) *ListSecurityScansForResourceParams {
	var ()
	return &ListSecurityScansForResourceParams{

		timeout: timeout,
	}
}

// NewListSecurityScansForResourceParamsWithContext creates a new ListSecurityScansForResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewListSecurityScansForResourceParamsWithContext(ctx context.Context) *ListSecurityScansForResourceParams {
	var ()
	return &ListSecurityScansForResourceParams{

		Context: ctx,
	}
}

// NewListSecurityScansForResourceParamsWithHTTPClient creates a new ListSecurityScansForResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListSecurityScansForResourceParamsWithHTTPClient(client *http.Client) *ListSecurityScansForResourceParams {
	var ()
	return &ListSecurityScansForResourceParams{
		HTTPClient: client,
	}
}

/*ListSecurityScansForResourceParams contains all the parameters to send to the API endpoint
for the list security scans for resource operation typically these are written to a http.Request
*/
type ListSecurityScansForResourceParams struct {

	/*Group
	  Is the group of the kind

	*/
	Group string
	/*Kind
	  Is the kind of the resource

	*/
	Kind string
	/*Name
	  Is the name of the resource

	*/
	Name string
	/*Namespace
	  Is the namespace of the resource

	*/
	Namespace string
	/*Version
	  Is the version of the kind

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) WithTimeout(timeout time.Duration) *ListSecurityScansForResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) WithContext(ctx context.Context) *ListSecurityScansForResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) WithHTTPClient(client *http.Client) *ListSecurityScansForResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroup adds the group to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) WithGroup(group string) *ListSecurityScansForResourceParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) SetGroup(group string) {
	o.Group = group
}

// WithKind adds the kind to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) WithKind(kind string) *ListSecurityScansForResourceParams {
	o.SetKind(kind)
	return o
}

// SetKind adds the kind to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) SetKind(kind string) {
	o.Kind = kind
}

// WithName adds the name to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) WithName(name string) *ListSecurityScansForResourceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) SetName(name string) {
	o.Name = name
}

// WithNamespace adds the namespace to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) WithNamespace(namespace string) *ListSecurityScansForResourceParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithVersion adds the version to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) WithVersion(version string) *ListSecurityScansForResourceParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the list security scans for resource params
func (o *ListSecurityScansForResourceParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *ListSecurityScansForResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group
	if err := r.SetPathParam("group", o.Group); err != nil {
		return err
	}

	// path param kind
	if err := r.SetPathParam("kind", o.Kind); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
