// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// ListSecurityScansReader is a Reader for the ListSecurityScans structure.
type ListSecurityScansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSecurityScansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSecurityScansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListSecurityScansUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListSecurityScansForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListSecurityScansInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListSecurityScansOK creates a ListSecurityScansOK with default headers values
func NewListSecurityScansOK() *ListSecurityScansOK {
	return &ListSecurityScansOK{}
}

/*ListSecurityScansOK handles this case with default header values.

A collection of security scans
*/
type ListSecurityScansOK struct {
	Payload *models.V1SecurityScanResultList
}

func (o *ListSecurityScansOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/security/scans][%d] listSecurityScansOK  %+v", 200, o.Payload)
}

func (o *ListSecurityScansOK) GetPayload() *models.V1SecurityScanResultList {
	return o.Payload
}

func (o *ListSecurityScansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1SecurityScanResultList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSecurityScansUnauthorized creates a ListSecurityScansUnauthorized with default headers values
func NewListSecurityScansUnauthorized() *ListSecurityScansUnauthorized {
	return &ListSecurityScansUnauthorized{}
}

/*ListSecurityScansUnauthorized handles this case with default header values.

If not authenticated
*/
type ListSecurityScansUnauthorized struct {
}

func (o *ListSecurityScansUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/security/scans][%d] listSecurityScansUnauthorized ", 401)
}

func (o *ListSecurityScansUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListSecurityScansForbidden creates a ListSecurityScansForbidden with default headers values
func NewListSecurityScansForbidden() *ListSecurityScansForbidden {
	return &ListSecurityScansForbidden{}
}

/*ListSecurityScansForbidden handles this case with default header values.

If authenticated but not authorized
*/
type ListSecurityScansForbidden struct {
}

func (o *ListSecurityScansForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/security/scans][%d] listSecurityScansForbidden ", 403)
}

func (o *ListSecurityScansForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListSecurityScansInternalServerError creates a ListSecurityScansInternalServerError with default headers values
func NewListSecurityScansInternalServerError() *ListSecurityScansInternalServerError {
	return &ListSecurityScansInternalServerError{}
}

/*ListSecurityScansInternalServerError handles this case with default header values.

A generic API error containing the cause of the error
*/
type ListSecurityScansInternalServerError struct {
	Payload *models.ApiserverError
}

func (o *ListSecurityScansInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/security/scans][%d] listSecurityScansInternalServerError  %+v", 500, o.Payload)
}

func (o *ListSecurityScansInternalServerError) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *ListSecurityScansInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
