// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// ListInvitesReader is a Reader for the ListInvites structure.
type ListInvitesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListInvitesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListInvitesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListInvitesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListInvitesOK creates a ListInvitesOK with default headers values
func NewListInvitesOK() *ListInvitesOK {
	return &ListInvitesOK{}
}

/*ListInvitesOK handles this case with default header values.

A list of users whom have an invitation for the team
*/
type ListInvitesOK struct {
	Payload *models.V1TeamInvitationList
}

func (o *ListInvitesOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/invites/user][%d] listInvitesOK  %+v", 200, o.Payload)
}

func (o *ListInvitesOK) GetPayload() *models.V1TeamInvitationList {
	return o.Payload
}

func (o *ListInvitesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamInvitationList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListInvitesInternalServerError creates a ListInvitesInternalServerError with default headers values
func NewListInvitesInternalServerError() *ListInvitesInternalServerError {
	return &ListInvitesInternalServerError{}
}

/*ListInvitesInternalServerError handles this case with default header values.

A generic API error containing the cause of the error
*/
type ListInvitesInternalServerError struct {
	Payload *models.ApiserverError
}

func (o *ListInvitesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/invites/user][%d] listInvitesInternalServerError  %+v", 500, o.Payload)
}

func (o *ListInvitesInternalServerError) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *ListInvitesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
