// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListInvitesParams creates a new ListInvitesParams object
// with the default values initialized.
func NewListInvitesParams() *ListInvitesParams {
	var ()
	return &ListInvitesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListInvitesParamsWithTimeout creates a new ListInvitesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListInvitesParamsWithTimeout(timeout time.Duration) *ListInvitesParams {
	var ()
	return &ListInvitesParams{

		timeout: timeout,
	}
}

// NewListInvitesParamsWithContext creates a new ListInvitesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListInvitesParamsWithContext(ctx context.Context) *ListInvitesParams {
	var ()
	return &ListInvitesParams{

		Context: ctx,
	}
}

// NewListInvitesParamsWithHTTPClient creates a new ListInvitesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListInvitesParamsWithHTTPClient(client *http.Client) *ListInvitesParams {
	var ()
	return &ListInvitesParams{
		HTTPClient: client,
	}
}

/*ListInvitesParams contains all the parameters to send to the API endpoint
for the list invites operation typically these are written to a http.Request
*/
type ListInvitesParams struct {

	/*Team
	  The name of the team you are pulling the invitations for

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list invites params
func (o *ListInvitesParams) WithTimeout(timeout time.Duration) *ListInvitesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list invites params
func (o *ListInvitesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list invites params
func (o *ListInvitesParams) WithContext(ctx context.Context) *ListInvitesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list invites params
func (o *ListInvitesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list invites params
func (o *ListInvitesParams) WithHTTPClient(client *http.Client) *ListInvitesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list invites params
func (o *ListInvitesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeam adds the team to the list invites params
func (o *ListInvitesParams) WithTeam(team string) *ListInvitesParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the list invites params
func (o *ListInvitesParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *ListInvitesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
