// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// ListUserTeamsReader is a Reader for the ListUserTeams structure.
type ListUserTeamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListUserTeamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListUserTeamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewListUserTeamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListUserTeamsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListUserTeamsOK creates a ListUserTeamsOK with default headers values
func NewListUserTeamsOK() *ListUserTeamsOK {
	return &ListUserTeamsOK{}
}

/*ListUserTeamsOK handles this case with default header values.

Response is a team list containing the teams the user is a member of
*/
type ListUserTeamsOK struct {
	Payload *models.V1TeamList
}

func (o *ListUserTeamsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/users/{user}/teams][%d] listUserTeamsOK  %+v", 200, o.Payload)
}

func (o *ListUserTeamsOK) GetPayload() *models.V1TeamList {
	return o.Payload
}

func (o *ListUserTeamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListUserTeamsNotFound creates a ListUserTeamsNotFound with default headers values
func NewListUserTeamsNotFound() *ListUserTeamsNotFound {
	return &ListUserTeamsNotFound{}
}

/*ListUserTeamsNotFound handles this case with default header values.

User does not exist
*/
type ListUserTeamsNotFound struct {
}

func (o *ListUserTeamsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/users/{user}/teams][%d] listUserTeamsNotFound ", 404)
}

func (o *ListUserTeamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListUserTeamsInternalServerError creates a ListUserTeamsInternalServerError with default headers values
func NewListUserTeamsInternalServerError() *ListUserTeamsInternalServerError {
	return &ListUserTeamsInternalServerError{}
}

/*ListUserTeamsInternalServerError handles this case with default header values.

A generic API error containing the cause of the error
*/
type ListUserTeamsInternalServerError struct {
	Payload *models.ApiserverError
}

func (o *ListUserTeamsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/users/{user}/teams][%d] listUserTeamsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListUserTeamsInternalServerError) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *ListUserTeamsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
