// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListUserIdentityParams creates a new ListUserIdentityParams object
// with the default values initialized.
func NewListUserIdentityParams() *ListUserIdentityParams {
	var ()
	return &ListUserIdentityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListUserIdentityParamsWithTimeout creates a new ListUserIdentityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListUserIdentityParamsWithTimeout(timeout time.Duration) *ListUserIdentityParams {
	var ()
	return &ListUserIdentityParams{

		timeout: timeout,
	}
}

// NewListUserIdentityParamsWithContext creates a new ListUserIdentityParams object
// with the default values initialized, and the ability to set a context for a request
func NewListUserIdentityParamsWithContext(ctx context.Context) *ListUserIdentityParams {
	var ()
	return &ListUserIdentityParams{

		Context: ctx,
	}
}

// NewListUserIdentityParamsWithHTTPClient creates a new ListUserIdentityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListUserIdentityParamsWithHTTPClient(client *http.Client) *ListUserIdentityParams {
	var ()
	return &ListUserIdentityParams{
		HTTPClient: client,
	}
}

/*ListUserIdentityParams contains all the parameters to send to the API endpoint
for the list user identity operation typically these are written to a http.Request
*/
type ListUserIdentityParams struct {

	/*User
	  The name of the user you wish to retrieve identities for

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list user identity params
func (o *ListUserIdentityParams) WithTimeout(timeout time.Duration) *ListUserIdentityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list user identity params
func (o *ListUserIdentityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list user identity params
func (o *ListUserIdentityParams) WithContext(ctx context.Context) *ListUserIdentityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list user identity params
func (o *ListUserIdentityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list user identity params
func (o *ListUserIdentityParams) WithHTTPClient(client *http.Client) *ListUserIdentityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list user identity params
func (o *ListUserIdentityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the list user identity params
func (o *ListUserIdentityParams) WithUser(user string) *ListUserIdentityParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the list user identity params
func (o *ListUserIdentityParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *ListUserIdentityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
