// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/apiclient/models"
)

// LocalAuthorizeReader is a Reader for the LocalAuthorize structure.
type LocalAuthorizeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LocalAuthorizeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLocalAuthorizeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewLocalAuthorizeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLocalAuthorizeOK creates a LocalAuthorizeOK with default headers values
func NewLocalAuthorizeOK() *LocalAuthorizeOK {
	return &LocalAuthorizeOK{}
}

/*LocalAuthorizeOK handles this case with default header values.

OK
*/
type LocalAuthorizeOK struct {
}

func (o *LocalAuthorizeOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1alpha1/issue/authorize][%d] localAuthorizeOK ", 200)
}

func (o *LocalAuthorizeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLocalAuthorizeDefault creates a LocalAuthorizeDefault with default headers values
func NewLocalAuthorizeDefault(code int) *LocalAuthorizeDefault {
	return &LocalAuthorizeDefault{
		_statusCode: code,
	}
}

/*LocalAuthorizeDefault handles this case with default header values.

A generic API error containing the cause of the error
*/
type LocalAuthorizeDefault struct {
	_statusCode int

	Payload *models.ApiserverError
}

// Code gets the status code for the local authorize default response
func (o *LocalAuthorizeDefault) Code() int {
	return o._statusCode
}

func (o *LocalAuthorizeDefault) Error() string {
	return fmt.Sprintf("[PUT /api/v1alpha1/issue/authorize][%d] LocalAuthorize default  %+v", o._statusCode, o.Payload)
}

func (o *LocalAuthorizeDefault) GetPayload() *models.ApiserverError {
	return o.Payload
}

func (o *LocalAuthorizeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
