// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemovePlanPolicyParams creates a new RemovePlanPolicyParams object
// with the default values initialized.
func NewRemovePlanPolicyParams() *RemovePlanPolicyParams {
	var ()
	return &RemovePlanPolicyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemovePlanPolicyParamsWithTimeout creates a new RemovePlanPolicyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemovePlanPolicyParamsWithTimeout(timeout time.Duration) *RemovePlanPolicyParams {
	var ()
	return &RemovePlanPolicyParams{

		timeout: timeout,
	}
}

// NewRemovePlanPolicyParamsWithContext creates a new RemovePlanPolicyParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemovePlanPolicyParamsWithContext(ctx context.Context) *RemovePlanPolicyParams {
	var ()
	return &RemovePlanPolicyParams{

		Context: ctx,
	}
}

// NewRemovePlanPolicyParamsWithHTTPClient creates a new RemovePlanPolicyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemovePlanPolicyParamsWithHTTPClient(client *http.Client) *RemovePlanPolicyParams {
	var ()
	return &RemovePlanPolicyParams{
		HTTPClient: client,
	}
}

/*RemovePlanPolicyParams contains all the parameters to send to the API endpoint
for the remove plan policy operation typically these are written to a http.Request
*/
type RemovePlanPolicyParams struct {

	/*Name
	  The name of the plan policy you wish to delete

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove plan policy params
func (o *RemovePlanPolicyParams) WithTimeout(timeout time.Duration) *RemovePlanPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove plan policy params
func (o *RemovePlanPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove plan policy params
func (o *RemovePlanPolicyParams) WithContext(ctx context.Context) *RemovePlanPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove plan policy params
func (o *RemovePlanPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove plan policy params
func (o *RemovePlanPolicyParams) WithHTTPClient(client *http.Client) *RemovePlanPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove plan policy params
func (o *RemovePlanPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the remove plan policy params
func (o *RemovePlanPolicyParams) WithName(name string) *RemovePlanPolicyParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the remove plan policy params
func (o *RemovePlanPolicyParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *RemovePlanPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
