// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveGKEParams creates a new RemoveGKEParams object
// with the default values initialized.
func NewRemoveGKEParams() *RemoveGKEParams {
	var ()
	return &RemoveGKEParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveGKEParamsWithTimeout creates a new RemoveGKEParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveGKEParamsWithTimeout(timeout time.Duration) *RemoveGKEParams {
	var ()
	return &RemoveGKEParams{

		timeout: timeout,
	}
}

// NewRemoveGKEParamsWithContext creates a new RemoveGKEParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveGKEParamsWithContext(ctx context.Context) *RemoveGKEParams {
	var ()
	return &RemoveGKEParams{

		Context: ctx,
	}
}

// NewRemoveGKEParamsWithHTTPClient creates a new RemoveGKEParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoveGKEParamsWithHTTPClient(client *http.Client) *RemoveGKEParams {
	var ()
	return &RemoveGKEParams{
		HTTPClient: client,
	}
}

/*RemoveGKEParams contains all the parameters to send to the API endpoint
for the remove g k e operation typically these are written to a http.Request
*/
type RemoveGKEParams struct {

	/*Name
	  Is name the of the GKE cluster you are acting upon

	*/
	Name string
	/*Team
	  Is the name of the team you are acting within

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove g k e params
func (o *RemoveGKEParams) WithTimeout(timeout time.Duration) *RemoveGKEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove g k e params
func (o *RemoveGKEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove g k e params
func (o *RemoveGKEParams) WithContext(ctx context.Context) *RemoveGKEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove g k e params
func (o *RemoveGKEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove g k e params
func (o *RemoveGKEParams) WithHTTPClient(client *http.Client) *RemoveGKEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove g k e params
func (o *RemoveGKEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the remove g k e params
func (o *RemoveGKEParams) WithName(name string) *RemoveGKEParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the remove g k e params
func (o *RemoveGKEParams) SetName(name string) {
	o.Name = name
}

// WithTeam adds the team to the remove g k e params
func (o *RemoveGKEParams) WithTeam(team string) *RemoveGKEParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the remove g k e params
func (o *RemoveGKEParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveGKEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
