// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveNamespaceParams creates a new RemoveNamespaceParams object
// with the default values initialized.
func NewRemoveNamespaceParams() *RemoveNamespaceParams {
	var ()
	return &RemoveNamespaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveNamespaceParamsWithTimeout creates a new RemoveNamespaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveNamespaceParamsWithTimeout(timeout time.Duration) *RemoveNamespaceParams {
	var ()
	return &RemoveNamespaceParams{

		timeout: timeout,
	}
}

// NewRemoveNamespaceParamsWithContext creates a new RemoveNamespaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveNamespaceParamsWithContext(ctx context.Context) *RemoveNamespaceParams {
	var ()
	return &RemoveNamespaceParams{

		Context: ctx,
	}
}

// NewRemoveNamespaceParamsWithHTTPClient creates a new RemoveNamespaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoveNamespaceParamsWithHTTPClient(client *http.Client) *RemoveNamespaceParams {
	var ()
	return &RemoveNamespaceParams{
		HTTPClient: client,
	}
}

/*RemoveNamespaceParams contains all the parameters to send to the API endpoint
for the remove namespace operation typically these are written to a http.Request
*/
type RemoveNamespaceParams struct {

	/*Name
	  Is name the of the namespace claim you are acting upon

	*/
	Name string
	/*Team
	  Is the name of the team you are acting within

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove namespace params
func (o *RemoveNamespaceParams) WithTimeout(timeout time.Duration) *RemoveNamespaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove namespace params
func (o *RemoveNamespaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove namespace params
func (o *RemoveNamespaceParams) WithContext(ctx context.Context) *RemoveNamespaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove namespace params
func (o *RemoveNamespaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove namespace params
func (o *RemoveNamespaceParams) WithHTTPClient(client *http.Client) *RemoveNamespaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove namespace params
func (o *RemoveNamespaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the remove namespace params
func (o *RemoveNamespaceParams) WithName(name string) *RemoveNamespaceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the remove namespace params
func (o *RemoveNamespaceParams) SetName(name string) {
	o.Name = name
}

// WithTeam adds the team to the remove namespace params
func (o *RemoveNamespaceParams) WithTeam(team string) *RemoveNamespaceParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the remove namespace params
func (o *RemoveNamespaceParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveNamespaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
