// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSecurityScanParams creates a new GetSecurityScanParams object
// with the default values initialized.
func NewGetSecurityScanParams() *GetSecurityScanParams {
	var ()
	return &GetSecurityScanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSecurityScanParamsWithTimeout creates a new GetSecurityScanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSecurityScanParamsWithTimeout(timeout time.Duration) *GetSecurityScanParams {
	var ()
	return &GetSecurityScanParams{

		timeout: timeout,
	}
}

// NewGetSecurityScanParamsWithContext creates a new GetSecurityScanParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSecurityScanParamsWithContext(ctx context.Context) *GetSecurityScanParams {
	var ()
	return &GetSecurityScanParams{

		Context: ctx,
	}
}

// NewGetSecurityScanParamsWithHTTPClient creates a new GetSecurityScanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSecurityScanParamsWithHTTPClient(client *http.Client) *GetSecurityScanParams {
	var ()
	return &GetSecurityScanParams{
		HTTPClient: client,
	}
}

/*GetSecurityScanParams contains all the parameters to send to the API endpoint
for the get security scan operation typically these are written to a http.Request
*/
type GetSecurityScanParams struct {

	/*ID
	  Is the ID of the scan

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get security scan params
func (o *GetSecurityScanParams) WithTimeout(timeout time.Duration) *GetSecurityScanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get security scan params
func (o *GetSecurityScanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get security scan params
func (o *GetSecurityScanParams) WithContext(ctx context.Context) *GetSecurityScanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get security scan params
func (o *GetSecurityScanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get security scan params
func (o *GetSecurityScanParams) WithHTTPClient(client *http.Client) *GetSecurityScanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get security scan params
func (o *GetSecurityScanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get security scan params
func (o *GetSecurityScanParams) WithID(id int64) *GetSecurityScanParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get security scan params
func (o *GetSecurityScanParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSecurityScanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
