// Code generated by go-swagger; DO NOT EDIT.

package costs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListCostsParams creates a new ListCostsParams object
// with the default values initialized.
func NewListCostsParams() *ListCostsParams {

	return &ListCostsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListCostsParamsWithTimeout creates a new ListCostsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListCostsParamsWithTimeout(timeout time.Duration) *ListCostsParams {

	return &ListCostsParams{

		timeout: timeout,
	}
}

// NewListCostsParamsWithContext creates a new ListCostsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListCostsParamsWithContext(ctx context.Context) *ListCostsParams {

	return &ListCostsParams{

		Context: ctx,
	}
}

// NewListCostsParamsWithHTTPClient creates a new ListCostsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListCostsParamsWithHTTPClient(client *http.Client) *ListCostsParams {

	return &ListCostsParams{
		HTTPClient: client,
	}
}

/*ListCostsParams contains all the parameters to send to the API endpoint
for the list costs operation typically these are written to a http.Request
*/
type ListCostsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list costs params
func (o *ListCostsParams) WithTimeout(timeout time.Duration) *ListCostsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list costs params
func (o *ListCostsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list costs params
func (o *ListCostsParams) WithContext(ctx context.Context) *ListCostsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list costs params
func (o *ListCostsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list costs params
func (o *ListCostsParams) WithHTTPClient(client *http.Client) *ListCostsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list costs params
func (o *ListCostsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListCostsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
