// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SecurityResourceOverview v1 security resource overview
//
// swagger:model v1.SecurityResourceOverview
type V1SecurityResourceOverview struct {

	// last checked
	LastChecked string `json:"lastChecked,omitempty"`

	// open issue counts
	OpenIssueCounts map[string]int64 `json:"openIssueCounts,omitempty"`

	// overall status
	OverallStatus string `json:"overallStatus,omitempty"`

	// resource
	Resource *V1Ownership `json:"resource,omitempty"`
}

// Validate validates this v1 security resource overview
func (m *V1SecurityResourceOverview) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SecurityResourceOverview) validateResource(formats strfmt.Registry) error {

	if swag.IsZero(m.Resource) { // not required
		return nil
	}

	if m.Resource != nil {
		if err := m.Resource.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resource")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1SecurityResourceOverview) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SecurityResourceOverview) UnmarshalBinary(b []byte) error {
	var res V1SecurityResourceOverview
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
