// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1beta1TeamCostSummary v1beta1 team cost summary
//
// swagger:model v1beta1.TeamCostSummary
type V1beta1TeamCostSummary struct {

	// asset costs
	// Required: true
	AssetCosts []*V1beta1AssetCostSummary `json:"assetCosts"`

	// cost
	// Required: true
	Cost *int64 `json:"cost"`

	// team identifier
	TeamIdentifier string `json:"teamIdentifier,omitempty"`

	// team name
	TeamName string `json:"teamName,omitempty"`

	// usage end time
	UsageEndTime string `json:"usageEndTime,omitempty"`

	// usage start time
	UsageStartTime string `json:"usageStartTime,omitempty"`
}

// Validate validates this v1beta1 team cost summary
func (m *V1beta1TeamCostSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssetCosts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCost(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1TeamCostSummary) validateAssetCosts(formats strfmt.Registry) error {

	if err := validate.Required("assetCosts", "body", m.AssetCosts); err != nil {
		return err
	}

	for i := 0; i < len(m.AssetCosts); i++ {
		if swag.IsZero(m.AssetCosts[i]) { // not required
			continue
		}

		if m.AssetCosts[i] != nil {
			if err := m.AssetCosts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("assetCosts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1beta1TeamCostSummary) validateCost(formats strfmt.Registry) error {

	if err := validate.Required("cost", "body", m.Cost); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1TeamCostSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1TeamCostSummary) UnmarshalBinary(b []byte) error {
	var res V1beta1TeamCostSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
