// Code generated by go-swagger; DO NOT EDIT.

package costestimates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEstimateClusterPlanCostParams creates a new EstimateClusterPlanCostParams object
// with the default values initialized.
func NewEstimateClusterPlanCostParams() *EstimateClusterPlanCostParams {

	return &EstimateClusterPlanCostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEstimateClusterPlanCostParamsWithTimeout creates a new EstimateClusterPlanCostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEstimateClusterPlanCostParamsWithTimeout(timeout time.Duration) *EstimateClusterPlanCostParams {

	return &EstimateClusterPlanCostParams{

		timeout: timeout,
	}
}

// NewEstimateClusterPlanCostParamsWithContext creates a new EstimateClusterPlanCostParams object
// with the default values initialized, and the ability to set a context for a request
func NewEstimateClusterPlanCostParamsWithContext(ctx context.Context) *EstimateClusterPlanCostParams {

	return &EstimateClusterPlanCostParams{

		Context: ctx,
	}
}

// NewEstimateClusterPlanCostParamsWithHTTPClient creates a new EstimateClusterPlanCostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEstimateClusterPlanCostParamsWithHTTPClient(client *http.Client) *EstimateClusterPlanCostParams {

	return &EstimateClusterPlanCostParams{
		HTTPClient: client,
	}
}

/*EstimateClusterPlanCostParams contains all the parameters to send to the API endpoint
for the estimate cluster plan cost operation typically these are written to a http.Request
*/
type EstimateClusterPlanCostParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the estimate cluster plan cost params
func (o *EstimateClusterPlanCostParams) WithTimeout(timeout time.Duration) *EstimateClusterPlanCostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the estimate cluster plan cost params
func (o *EstimateClusterPlanCostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the estimate cluster plan cost params
func (o *EstimateClusterPlanCostParams) WithContext(ctx context.Context) *EstimateClusterPlanCostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the estimate cluster plan cost params
func (o *EstimateClusterPlanCostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the estimate cluster plan cost params
func (o *EstimateClusterPlanCostParams) WithHTTPClient(client *http.Client) *EstimateClusterPlanCostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the estimate cluster plan cost params
func (o *EstimateClusterPlanCostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *EstimateClusterPlanCostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
