// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/testing/apimodels"
)

// GetTeamMembersReader is a Reader for the GetTeamMembers structure.
type GetTeamMembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTeamMembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTeamMembersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetTeamMembersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTeamMembersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTeamMembersOK creates a GetTeamMembersOK with default headers values
func NewGetTeamMembersOK() *GetTeamMembersOK {
	return &GetTeamMembersOK{}
}

/*GetTeamMembersOK handles this case with default header values.

Contains a collection of team memberships for this team
*/
type GetTeamMembersOK struct {
	Payload *apimodels.V1TeamMemberList
}

func (o *GetTeamMembersOK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/members][%d] getTeamMembersOK  %+v", 200, o.Payload)
}

func (o *GetTeamMembersOK) GetPayload() *apimodels.V1TeamMemberList {
	return o.Payload
}

func (o *GetTeamMembersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodels.V1TeamMemberList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTeamMembersNotFound creates a GetTeamMembersNotFound with default headers values
func NewGetTeamMembersNotFound() *GetTeamMembersNotFound {
	return &GetTeamMembersNotFound{}
}

/*GetTeamMembersNotFound handles this case with default header values.

Team does not exist
*/
type GetTeamMembersNotFound struct {
}

func (o *GetTeamMembersNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/members][%d] getTeamMembersNotFound ", 404)
}

func (o *GetTeamMembersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTeamMembersInternalServerError creates a GetTeamMembersInternalServerError with default headers values
func NewGetTeamMembersInternalServerError() *GetTeamMembersInternalServerError {
	return &GetTeamMembersInternalServerError{}
}

/*GetTeamMembersInternalServerError handles this case with default header values.

A generic API error containing the cause of the error
*/
type GetTeamMembersInternalServerError struct {
	Payload *apimodels.ApiserverError
}

func (o *GetTeamMembersInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/teams/{team}/members][%d] getTeamMembersInternalServerError  %+v", 500, o.Payload)
}

func (o *GetTeamMembersInternalServerError) GetPayload() *apimodels.ApiserverError {
	return o.Payload
}

func (o *GetTeamMembersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodels.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
