// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDefaultIDPParams creates a new GetDefaultIDPParams object
// with the default values initialized.
func NewGetDefaultIDPParams() *GetDefaultIDPParams {

	return &GetDefaultIDPParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDefaultIDPParamsWithTimeout creates a new GetDefaultIDPParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDefaultIDPParamsWithTimeout(timeout time.Duration) *GetDefaultIDPParams {

	return &GetDefaultIDPParams{

		timeout: timeout,
	}
}

// NewGetDefaultIDPParamsWithContext creates a new GetDefaultIDPParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDefaultIDPParamsWithContext(ctx context.Context) *GetDefaultIDPParams {

	return &GetDefaultIDPParams{

		Context: ctx,
	}
}

// NewGetDefaultIDPParamsWithHTTPClient creates a new GetDefaultIDPParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDefaultIDPParamsWithHTTPClient(client *http.Client) *GetDefaultIDPParams {

	return &GetDefaultIDPParams{
		HTTPClient: client,
	}
}

/*GetDefaultIDPParams contains all the parameters to send to the API endpoint
for the get default ID p operation typically these are written to a http.Request
*/
type GetDefaultIDPParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get default ID p params
func (o *GetDefaultIDPParams) WithTimeout(timeout time.Duration) *GetDefaultIDPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get default ID p params
func (o *GetDefaultIDPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get default ID p params
func (o *GetDefaultIDPParams) WithContext(ctx context.Context) *GetDefaultIDPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get default ID p params
func (o *GetDefaultIDPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get default ID p params
func (o *GetDefaultIDPParams) WithHTTPClient(client *http.Client) *GetDefaultIDPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get default ID p params
func (o *GetDefaultIDPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDefaultIDPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
