// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListIDPsParams creates a new ListIDPsParams object
// with the default values initialized.
func NewListIDPsParams() *ListIDPsParams {

	return &ListIDPsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListIDPsParamsWithTimeout creates a new ListIDPsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListIDPsParamsWithTimeout(timeout time.Duration) *ListIDPsParams {

	return &ListIDPsParams{

		timeout: timeout,
	}
}

// NewListIDPsParamsWithContext creates a new ListIDPsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListIDPsParamsWithContext(ctx context.Context) *ListIDPsParams {

	return &ListIDPsParams{

		Context: ctx,
	}
}

// NewListIDPsParamsWithHTTPClient creates a new ListIDPsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListIDPsParamsWithHTTPClient(client *http.Client) *ListIDPsParams {

	return &ListIDPsParams{
		HTTPClient: client,
	}
}

/*ListIDPsParams contains all the parameters to send to the API endpoint
for the list ID ps operation typically these are written to a http.Request
*/
type ListIDPsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list ID ps params
func (o *ListIDPsParams) WithTimeout(timeout time.Duration) *ListIDPsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list ID ps params
func (o *ListIDPsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list ID ps params
func (o *ListIDPsParams) WithContext(ctx context.Context) *ListIDPsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list ID ps params
func (o *ListIDPsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list ID ps params
func (o *ListIDPsParams) WithHTTPClient(client *http.Client) *ListIDPsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list ID ps params
func (o *ListIDPsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListIDPsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
