// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/appvia/kore/pkg/testing/apimodels"
)

// RemoveUserReader is a Reader for the RemoveUser structure.
type RemoveUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemoveUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewRemoveUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemoveUserOK creates a RemoveUserOK with default headers values
func NewRemoveUserOK() *RemoveUserOK {
	return &RemoveUserOK{}
}

/*RemoveUserOK handles this case with default header values.

Contains the former user definition from the kore
*/
type RemoveUserOK struct {
	Payload *apimodels.V1User
}

func (o *RemoveUserOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1alpha1/users/{user}][%d] removeUserOK  %+v", 200, o.Payload)
}

func (o *RemoveUserOK) GetPayload() *apimodels.V1User {
	return o.Payload
}

func (o *RemoveUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodels.V1User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveUserInternalServerError creates a RemoveUserInternalServerError with default headers values
func NewRemoveUserInternalServerError() *RemoveUserInternalServerError {
	return &RemoveUserInternalServerError{}
}

/*RemoveUserInternalServerError handles this case with default header values.

A generic API error containing the cause of the error
*/
type RemoveUserInternalServerError struct {
	Payload *apimodels.ApiserverError
}

func (o *RemoveUserInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api/v1alpha1/users/{user}][%d] removeUserInternalServerError  %+v", 500, o.Payload)
}

func (o *RemoveUserInternalServerError) GetPayload() *apimodels.ApiserverError {
	return o.Payload
}

func (o *RemoveUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodels.ApiserverError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
