---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kore.name" . }}-apiserver
  {{- if .Values.api.endpoint.detect }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  {{- end }}
  labels:
    name: {{ include "kore.name" . }}-apiserver
{{ include "kore.labels" . | indent 4}}
spec:
  type: {{ .Values.api.serviceType }}
  ports:
  - name: http
    port: {{ .Values.api.port }}
    targetPort: 10080
  selector:
    name: {{ include "kore.name" . }}-apiserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kore.name" . }}-apiserver
  labels:
{{ include "kore.labels" . | indent 4}}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      name: {{ include "kore.name" . }}-apiserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: {{ include "kore.name" . }}-apiserver
        service: {{ include "kore.name" . }}-apiserver
{{ include "kore.labels" . | indent 8}}
      annotations:
        prometheus.io/port: {{ .Values.api.metrics_port | quote }}
        prometheus.io/scheme: "http"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: {{ include "kore.name" . }}-admin
      containers:
      - name: {{ include "kore.name" . }}-apiserver
        image: {{ .Values.api.image }}:{{ .Values.api.version }}
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 10080
            {{- if .Values.api.hostPort }}
            hostPort: {{ .Values.api.hostPort }}
            {{- end }}
          {{- if .Values.api.enable_metrics }}
          - name: metrics
            containerPort: {{ .Values.api.metrics_port }}
          {{- end }}
          {{- if .Values.api.enable_profiling }}
          - name: pprof
            containerPort: {{ .Values.api.profiling_port }}
          {{- end }}
        envFrom:
          - secretRef:
              name: {{ include "kore.name" . }}-mysql
          - secretRef:
              name: {{ include "kore.name" . }}-idp
          - secretRef:
              name: {{ include "kore.name" . }}-api
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10080
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10080
          initialDelaySeconds: 30
        env:
          {{- if .Values.api.images.auth_proxy }}
          - name: AUTH_PROXY_IMAGE
            value: {{ .Values.api.images.auth_proxy }}
          {{- end }}
          {{- if .Values.api.build }}
          - name: BUILD_ID
            value: {{ .Values.api.build }}
          {{- end }}
          - name: KORE_ENABLE_MANAGED_DEPS
            value: "true"
          - name: KUBE_IN_CLUSTER
            value: "true"
          - name: KORE_CERTIFICATE_AUTHORITY
            value: /ca/ca.pem
          - name: KORE_CERTIFICATE_AUTHORITY_KEY
            value: /ca/ca-key.pem
          - name: KORE_API_PUBLIC_URL
            {{- if and (eq .Values.api.serviceType "LoadBalancer") .Values.api.endpoint.detect}}
            valueFrom:
              secretKeyRef:
                name: {{ include "kore.name" . }}-discovered-endpoints
                key: {{ include "kore.name" . }}-apiserver
            {{- else }}
            value: {{ .Values.api.endpoint.url }}
            {{- end }}
          - name: KORE_UI_PUBLIC_URL
            {{- if and (eq .Values.ui.serviceType "LoadBalancer") .Values.ui.endpoint.detect}}
            valueFrom:
              secretKeyRef:
                name: {{ include "kore.name" . }}-discovered-endpoints
                key: {{ include "kore.name" . }}-portal
            {{- else }}
            value: {{ .Values.ui.endpoint.url }}
            {{- end }}
          - name: KORE_AUTHENTICATION_PLUGINS
            value: {{ .Values.api.auth_plugins | join "," }}
          {{- if .Values.api.auth_plugin_config.local_jwt_publickey }}
          - name: KORE_LOCAL_JWT_PUBLIC_KEY
            value: "{{ .Values.api.auth_plugin_config.local_jwt_publickey }}"
          {{- end }}
          {{- if .Values.api.feature_gates }}
          - name: KORE_FEATURE_GATES
            value: "{{ join "," .Values.api.feature_gates }}"
          {{- end }}
          - name: VERBOSE
            value: "{{ .Values.api.verbose }}"
          - name: ENABLE_PROFILING
            value: "{{ .Values.api.enable_profiling }}"
          - name: PROFILING_PORT
            value: "{{ .Values.api.profiling_port }}"
          - name: ENABLE_METRICS
            value: "{{ .Values.api.enable_metrics }}"
          - name: METRICS_PORT
            value: "{{ .Values.api.metrics_port }}"
          - name: ENABLE_USER_DB_LOGGING
            value: "{{ .Values.api.verbose_db }}"
        volumeMounts:
        - name: ca
          readOnly: true
          mountPath: /ca
        {{ if eq .Values.api.version "dev" -}}
        - name: kore
          mountPath: /go/src/github.com/appvia/kore
        - name: gocache
          mountPath: /root/.cache/go-build
        {{- end }}
      volumes:
      - name: ca
        secret:
          secretName: {{ .Values.ca.secretName }}
      {{ if eq .Values.api.version "dev" -}}
      - name: kore
        hostPath:
          path: /go/src/github.com/appvia/kore
          type: Directory
      - name: gocache
        persistentVolumeClaim:
          claimName: {{ include "kore.name" . }}-gocache
      {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kore.name" . }}-admin
  labels:
{{ include "kore.labels" . | indent 4}}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "kore.name" . }}-admin
  labels:
{{ include "kore.labels" . | indent 4}}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "kore.name" . }}-admin
  namespace: {{ .Release.Namespace }}

{{ if eq .Values.api.version "dev" -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kore.name" . }}-gocache
  labels:
{{ include "kore.labels" . | indent 4}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}
