---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kore.name" . }}-portal
  {{- if .Values.ui.endpoint.detect}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  {{- end }}
  labels:
    name: {{ include "kore.name" . }}-portal
{{ include "kore.labels" . | indent 4}}
spec:
  type: {{ .Values.ui.serviceType }}
  ports:
  - name: {{ include "kore.name" . }}-portal
    port: {{ .Values.ui.port }}
    targetPort: 3000
  selector:
    name: {{ include "kore.name" . }}-portal

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kore.name" . }}-portal
  labels:
{{ include "kore.labels" . | indent 4}}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      name: {{ include "kore.name" . }}-portal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: {{ include "kore.name" . }}-portal
        service: {{ include "kore.name" . }}-portal
{{ include "kore.labels" . | indent 8}}
    spec:
      containers:
      - name: {{ include "kore.name" . }}-portal
        image: {{ .Values.ui.image }}:{{ .Values.ui.version }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          {{- if .Values.ui.hostPort }}
          hostPort: {{ .Values.ui.hostPort }}
          {{- end }}
        env:
        {{- if .Values.ui.build }}
        - name: BUILD_ID
          value: {{ .Values.ui.build }}
        {{- end }}
        - name: REDIS_URL
          value: redis://{{ include "kore.name" . }}-redis:6379
        - name: KORE_BASE_URL
          {{- if and (eq .Values.api.serviceType "LoadBalancer") .Values.api.endpoint.detect}}
          valueFrom:
            secretKeyRef:
              name: {{ include "kore.name" . }}-discovered-endpoints
              key: {{ include "kore.name" . }}-portal
          {{- else }}
          value: {{ .Values.ui.endpoint.url }}
          {{- end }}
        - name: KORE_API_URL
          value: http://{{ include "kore.name" . }}-apiserver:10080/api/v1alpha1
        {{- if .Values.ui.show_prototypes }}
        - name: KORE_UI_SHOW_PROTOTYPES
          value: "{{ .Values.ui.show_prototypes }}"
        {{- end }}
        {{- if .Values.ui.disable_animations }}
        - name: KORE_UI_DISABLE_ANIMATIONS
          value: "{{ .Values.ui.disable_animations }}"
        {{- end }}
        - name: KORE_API_PUBLIC_URL
          {{- if and (eq .Values.api.serviceType "LoadBalancer") .Values.api.endpoint.detect}}
          valueFrom:
            secretKeyRef:
              name: {{ include "kore.name" . }}-discovered-endpoints
              key: {{ include "kore.name" . }}-apiserver
          {{- else }}
          value: {{ .Values.api.endpoint.url }}
          {{- end }}
        - name: KORE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "kore.name" . }}-api
              key: KORE_ADMIN_TOKEN
        {{- if .Values.ui.feature_gates }}
        - name: KORE_FEATURE_GATES
          value: "{{ join "," .Values.ui.feature_gates }}"
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ include "kore.name" . }}-idp
        {{ if eq .Values.ui.version "dev" -}}
        volumeMounts:
        - name: kore
          mountPath: /go/src/github.com/appvia/kore
        {{- end }}
      {{ if eq .Values.ui.version "dev" -}}
      volumes:
      - name: kore
        hostPath:
          path: /go/src/github.com/appvia/kore
          type: Directory
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kore.name" . }}-redis
  labels:
    name: {{ include "kore.name" . }}-redis
{{ include "kore.labels" . | indent 4}}
spec:
  type: ClusterIP
  ports:
  - name: {{ include "kore.name" . }}-redis
    port: 6379
    targetPort: 6379
  sessionAffinity: ClientIP
  selector:
    name: {{ include "kore.name" . }}-redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kore.name" . }}-redis
  labels:
{{ include "kore.labels" . | indent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "kore.name" . }}-redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: {{ include "kore.name" . }}-redis
        service: {{ include "kore.name" . }}-redis
{{ include "kore.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ include "kore.name" . }}-redis
        image: redis:{{ .Values.redis.version }}
