FROM golang:1.14-alpine3.11

ENV CGO_ENABLED=0

RUN apk add --no-cache ca-certificates git make

WORKDIR /go/src/github.com/appvia/kore

VOLUME /root/.cache/go-build

ENTRYPOINT [ "sh", "-c", "time make kore-apiserver && bin/kore-apiserver" ]
