/**
 * Appvia Kore API
 * Kore API provides the frontend API for the Appvia Kore (kore.appvia.io)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@appvia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1alpha1Infra model module.
 * @module model/V1alpha1Infra
 * @version 0.0.1
 */
class V1alpha1Infra {
    /**
     * Constructs a new <code>V1alpha1Infra</code>.
     * @alias module:model/V1alpha1Infra
     */
    constructor() { 
        
        V1alpha1Infra.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1alpha1Infra</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1alpha1Infra} obj Optional instance to populate.
     * @return {module:model/V1alpha1Infra} The populated <code>V1alpha1Infra</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1alpha1Infra();

            if (data.hasOwnProperty('securityGroupIDs')) {
                obj['securityGroupIDs'] = ApiClient.convertToType(data['securityGroupIDs'], ['String']);
            }
            if (data.hasOwnProperty('subnetIDs')) {
                obj['subnetIDs'] = ApiClient.convertToType(data['subnetIDs'], ['String']);
            }
        }
        return obj;
    }

/**
     * @return {Array.<String>}
     */
    getSecurityGroupIDs() {
        return this.securityGroupIDs;
    }

    /**
     * @param {Array.<String>} securityGroupIDs
     */
    setSecurityGroupIDs(securityGroupIDs) {
        this['securityGroupIDs'] = securityGroupIDs;
    }
/**
     * @return {Array.<String>}
     */
    getSubnetIDs() {
        return this.subnetIDs;
    }

    /**
     * @param {Array.<String>} subnetIDs
     */
    setSubnetIDs(subnetIDs) {
        this['subnetIDs'] = subnetIDs;
    }

}

/**
 * @member {Array.<String>} securityGroupIDs
 */
V1alpha1Infra.prototype['securityGroupIDs'] = undefined;

/**
 * @member {Array.<String>} subnetIDs
 */
V1alpha1Infra.prototype['subnetIDs'] = undefined;






export default V1alpha1Infra;

