/**
 * Appvia Kore API
 * Kore API provides the frontend API for the Appvia Kore (kore.appvia.io)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@appvia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1Component from './V1Component';
import V1Ownership from './V1Ownership';
import V1SecretReference from './V1SecretReference';

/**
 * The V1alpha1AccountClaimStatus model module.
 * @module model/V1alpha1AccountClaimStatus
 * @version 0.0.1
 */
class V1alpha1AccountClaimStatus {
    /**
     * Constructs a new <code>V1alpha1AccountClaimStatus</code>.
     * @alias module:model/V1alpha1AccountClaimStatus
     */
    constructor() { 
        
        V1alpha1AccountClaimStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1alpha1AccountClaimStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1alpha1AccountClaimStatus} obj Optional instance to populate.
     * @return {module:model/V1alpha1AccountClaimStatus} The populated <code>V1alpha1AccountClaimStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1alpha1AccountClaimStatus();

            if (data.hasOwnProperty('accountID')) {
                obj['accountID'] = ApiClient.convertToType(data['accountID'], 'String');
            }
            if (data.hasOwnProperty('accountRef')) {
                obj['accountRef'] = V1Ownership.constructFromObject(data['accountRef']);
            }
            if (data.hasOwnProperty('conditions')) {
                obj['conditions'] = ApiClient.convertToType(data['conditions'], [V1Component]);
            }
            if (data.hasOwnProperty('credentialRef')) {
                obj['credentialRef'] = V1SecretReference.constructFromObject(data['credentialRef']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {String}
     */
    getAccountID() {
        return this.accountID;
    }

    /**
     * @param {String} accountID
     */
    setAccountID(accountID) {
        this['accountID'] = accountID;
    }
/**
     * @return {module:model/V1Ownership}
     */
    getAccountRef() {
        return this.accountRef;
    }

    /**
     * @param {module:model/V1Ownership} accountRef
     */
    setAccountRef(accountRef) {
        this['accountRef'] = accountRef;
    }
/**
     * @return {Array.<module:model/V1Component>}
     */
    getConditions() {
        return this.conditions;
    }

    /**
     * @param {Array.<module:model/V1Component>} conditions
     */
    setConditions(conditions) {
        this['conditions'] = conditions;
    }
/**
     * @return {module:model/V1SecretReference}
     */
    getCredentialRef() {
        return this.credentialRef;
    }

    /**
     * @param {module:model/V1SecretReference} credentialRef
     */
    setCredentialRef(credentialRef) {
        this['credentialRef'] = credentialRef;
    }
/**
     * @return {String}
     */
    getStatus() {
        return this.status;
    }

    /**
     * @param {String} status
     */
    setStatus(status) {
        this['status'] = status;
    }

}

/**
 * @member {String} accountID
 */
V1alpha1AccountClaimStatus.prototype['accountID'] = undefined;

/**
 * @member {module:model/V1Ownership} accountRef
 */
V1alpha1AccountClaimStatus.prototype['accountRef'] = undefined;

/**
 * @member {Array.<module:model/V1Component>} conditions
 */
V1alpha1AccountClaimStatus.prototype['conditions'] = undefined;

/**
 * @member {module:model/V1SecretReference} credentialRef
 */
V1alpha1AccountClaimStatus.prototype['credentialRef'] = undefined;

/**
 * @member {String} status
 */
V1alpha1AccountClaimStatus.prototype['status'] = undefined;






export default V1alpha1AccountClaimStatus;

