/**
 * Kore API
 * Kore API provides the frontend API (kore.appvia.io)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@appvia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1alpha1NodeTaint from './V1alpha1NodeTaint';

/**
 * The V1alpha1AgentPoolProfile model module.
 * @module model/V1alpha1AgentPoolProfile
 * @version 0.0.1
 */
class V1alpha1AgentPoolProfile {
    /**
     * Constructs a new <code>V1alpha1AgentPoolProfile</code>.
     * @alias module:model/V1alpha1AgentPoolProfile
     * @param count {Number} 
     * @param maxCount {Number} 
     * @param minCount {Number} 
     * @param mode {String} 
     * @param name {String} 
     * @param osDiskSizeGB {Number} 
     * @param osType {String} 
     * @param vmSize {String} 
     */
    constructor(count, maxCount, minCount, mode, name, osDiskSizeGB, osType, vmSize) { 
        
        V1alpha1AgentPoolProfile.initialize(this, count, maxCount, minCount, mode, name, osDiskSizeGB, osType, vmSize);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, count, maxCount, minCount, mode, name, osDiskSizeGB, osType, vmSize) { 
        obj['count'] = count;
        obj['maxCount'] = maxCount;
        obj['minCount'] = minCount;
        obj['mode'] = mode;
        obj['name'] = name;
        obj['osDiskSizeGB'] = osDiskSizeGB;
        obj['osType'] = osType;
        obj['vmSize'] = vmSize;
    }

    /**
     * Constructs a <code>V1alpha1AgentPoolProfile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1alpha1AgentPoolProfile} obj Optional instance to populate.
     * @return {module:model/V1alpha1AgentPoolProfile} The populated <code>V1alpha1AgentPoolProfile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1alpha1AgentPoolProfile();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('enableAutoScaling')) {
                obj['enableAutoScaling'] = ApiClient.convertToType(data['enableAutoScaling'], 'Boolean');
            }
            if (data.hasOwnProperty('maxCount')) {
                obj['maxCount'] = ApiClient.convertToType(data['maxCount'], 'Number');
            }
            if (data.hasOwnProperty('maxPods')) {
                obj['maxPods'] = ApiClient.convertToType(data['maxPods'], 'Number');
            }
            if (data.hasOwnProperty('minCount')) {
                obj['minCount'] = ApiClient.convertToType(data['minCount'], 'Number');
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('nodeImageVersion')) {
                obj['nodeImageVersion'] = ApiClient.convertToType(data['nodeImageVersion'], 'String');
            }
            if (data.hasOwnProperty('nodeLabels')) {
                obj['nodeLabels'] = ApiClient.convertToType(data['nodeLabels'], {'String': 'String'});
            }
            if (data.hasOwnProperty('nodeTaints')) {
                obj['nodeTaints'] = ApiClient.convertToType(data['nodeTaints'], [V1alpha1NodeTaint]);
            }
            if (data.hasOwnProperty('osDiskSizeGB')) {
                obj['osDiskSizeGB'] = ApiClient.convertToType(data['osDiskSizeGB'], 'Number');
            }
            if (data.hasOwnProperty('osType')) {
                obj['osType'] = ApiClient.convertToType(data['osType'], 'String');
            }
            if (data.hasOwnProperty('vmSize')) {
                obj['vmSize'] = ApiClient.convertToType(data['vmSize'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {Number}
     */
    getCount() {
        return this.count;
    }

    /**
     * @param {Number} count
     */
    setCount(count) {
        this['count'] = count;
    }
/**
     * @return {Boolean}
     */
    getEnableAutoScaling() {
        return this.enableAutoScaling;
    }

    /**
     * @param {Boolean} enableAutoScaling
     */
    setEnableAutoScaling(enableAutoScaling) {
        this['enableAutoScaling'] = enableAutoScaling;
    }
/**
     * @return {Number}
     */
    getMaxCount() {
        return this.maxCount;
    }

    /**
     * @param {Number} maxCount
     */
    setMaxCount(maxCount) {
        this['maxCount'] = maxCount;
    }
/**
     * @return {Number}
     */
    getMaxPods() {
        return this.maxPods;
    }

    /**
     * @param {Number} maxPods
     */
    setMaxPods(maxPods) {
        this['maxPods'] = maxPods;
    }
/**
     * @return {Number}
     */
    getMinCount() {
        return this.minCount;
    }

    /**
     * @param {Number} minCount
     */
    setMinCount(minCount) {
        this['minCount'] = minCount;
    }
/**
     * @return {String}
     */
    getMode() {
        return this.mode;
    }

    /**
     * @param {String} mode
     */
    setMode(mode) {
        this['mode'] = mode;
    }
/**
     * @return {String}
     */
    getName() {
        return this.name;
    }

    /**
     * @param {String} name
     */
    setName(name) {
        this['name'] = name;
    }
/**
     * @return {String}
     */
    getNodeImageVersion() {
        return this.nodeImageVersion;
    }

    /**
     * @param {String} nodeImageVersion
     */
    setNodeImageVersion(nodeImageVersion) {
        this['nodeImageVersion'] = nodeImageVersion;
    }
/**
     * @return {Object.<String, String>}
     */
    getNodeLabels() {
        return this.nodeLabels;
    }

    /**
     * @param {Object.<String, String>} nodeLabels
     */
    setNodeLabels(nodeLabels) {
        this['nodeLabels'] = nodeLabels;
    }
/**
     * @return {Array.<module:model/V1alpha1NodeTaint>}
     */
    getNodeTaints() {
        return this.nodeTaints;
    }

    /**
     * @param {Array.<module:model/V1alpha1NodeTaint>} nodeTaints
     */
    setNodeTaints(nodeTaints) {
        this['nodeTaints'] = nodeTaints;
    }
/**
     * @return {Number}
     */
    getOsDiskSizeGB() {
        return this.osDiskSizeGB;
    }

    /**
     * @param {Number} osDiskSizeGB
     */
    setOsDiskSizeGB(osDiskSizeGB) {
        this['osDiskSizeGB'] = osDiskSizeGB;
    }
/**
     * @return {String}
     */
    getOsType() {
        return this.osType;
    }

    /**
     * @param {String} osType
     */
    setOsType(osType) {
        this['osType'] = osType;
    }
/**
     * @return {String}
     */
    getVmSize() {
        return this.vmSize;
    }

    /**
     * @param {String} vmSize
     */
    setVmSize(vmSize) {
        this['vmSize'] = vmSize;
    }

}

/**
 * @member {Number} count
 */
V1alpha1AgentPoolProfile.prototype['count'] = undefined;

/**
 * @member {Boolean} enableAutoScaling
 */
V1alpha1AgentPoolProfile.prototype['enableAutoScaling'] = undefined;

/**
 * @member {Number} maxCount
 */
V1alpha1AgentPoolProfile.prototype['maxCount'] = undefined;

/**
 * @member {Number} maxPods
 */
V1alpha1AgentPoolProfile.prototype['maxPods'] = undefined;

/**
 * @member {Number} minCount
 */
V1alpha1AgentPoolProfile.prototype['minCount'] = undefined;

/**
 * @member {String} mode
 */
V1alpha1AgentPoolProfile.prototype['mode'] = undefined;

/**
 * @member {String} name
 */
V1alpha1AgentPoolProfile.prototype['name'] = undefined;

/**
 * @member {String} nodeImageVersion
 */
V1alpha1AgentPoolProfile.prototype['nodeImageVersion'] = undefined;

/**
 * @member {Object.<String, String>} nodeLabels
 */
V1alpha1AgentPoolProfile.prototype['nodeLabels'] = undefined;

/**
 * @member {Array.<module:model/V1alpha1NodeTaint>} nodeTaints
 */
V1alpha1AgentPoolProfile.prototype['nodeTaints'] = undefined;

/**
 * @member {Number} osDiskSizeGB
 */
V1alpha1AgentPoolProfile.prototype['osDiskSizeGB'] = undefined;

/**
 * @member {String} osType
 */
V1alpha1AgentPoolProfile.prototype['osType'] = undefined;

/**
 * @member {String} vmSize
 */
V1alpha1AgentPoolProfile.prototype['vmSize'] = undefined;






export default V1alpha1AgentPoolProfile;

