/**
 * Appvia Kore API
 * Kore API provides the frontend API for the Appvia Kore (kore.appvia.io)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@appvia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1SecretSpec model module.
 * @module model/V1SecretSpec
 * @version 0.0.1
 */
class V1SecretSpec {
    /**
     * Constructs a new <code>V1SecretSpec</code>.
     * @alias module:model/V1SecretSpec
     * @param description {String} 
     * @param type {String} 
     */
    constructor(description, type) { 
        
        V1SecretSpec.initialize(this, description, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, description, type) { 
        obj['description'] = description;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>V1SecretSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1SecretSpec} obj Optional instance to populate.
     * @return {module:model/V1SecretSpec} The populated <code>V1SecretSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1SecretSpec();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], {'String': 'String'});
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {Object.<String, String>}
     */
    getData() {
        return this.data;
    }

    /**
     * @param {Object.<String, String>} data
     */
    setData(data) {
        this['data'] = data;
    }
/**
     * @return {String}
     */
    getDescription() {
        return this.description;
    }

    /**
     * @param {String} description
     */
    setDescription(description) {
        this['description'] = description;
    }
/**
     * @return {String}
     */
    getType() {
        return this.type;
    }

    /**
     * @param {String} type
     */
    setType(type) {
        this['type'] = type;
    }

}

/**
 * @member {Object.<String, String>} data
 */
V1SecretSpec.prototype['data'] = undefined;

/**
 * @member {String} description
 */
V1SecretSpec.prototype['description'] = undefined;

/**
 * @member {String} type
 */
V1SecretSpec.prototype['type'] = undefined;






export default V1SecretSpec;

