/**
 * Kore API
 * Kore API provides the frontend API (kore.appvia.io)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@appvia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ConfigurationFromSource from './V1ConfigurationFromSource';

/**
 * The V1ServiceProviderSpec model module.
 * @module model/V1ServiceProviderSpec
 * @version 0.0.1
 */
class V1ServiceProviderSpec {
    /**
     * Constructs a new <code>V1ServiceProviderSpec</code>.
     * @alias module:model/V1ServiceProviderSpec
     * @param summary {String} 
     * @param type {String} 
     */
    constructor(summary, type) { 
        
        V1ServiceProviderSpec.initialize(this, summary, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, summary, type) { 
        obj['summary'] = summary;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>V1ServiceProviderSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ServiceProviderSpec} obj Optional instance to populate.
     * @return {module:model/V1ServiceProviderSpec} The populated <code>V1ServiceProviderSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ServiceProviderSpec();

            if (data.hasOwnProperty('configuration')) {
                obj['configuration'] = ApiClient.convertToType(data['configuration'], Object);
            }
            if (data.hasOwnProperty('configurationFrom')) {
                obj['configurationFrom'] = ApiClient.convertToType(data['configurationFrom'], [V1ConfigurationFromSource]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {Object}
     */
    getConfiguration() {
        return this.configuration;
    }

    /**
     * @param {Object} configuration
     */
    setConfiguration(configuration) {
        this['configuration'] = configuration;
    }
/**
     * @return {Array.<module:model/V1ConfigurationFromSource>}
     */
    getConfigurationFrom() {
        return this.configurationFrom;
    }

    /**
     * @param {Array.<module:model/V1ConfigurationFromSource>} configurationFrom
     */
    setConfigurationFrom(configurationFrom) {
        this['configurationFrom'] = configurationFrom;
    }
/**
     * @return {String}
     */
    getDescription() {
        return this.description;
    }

    /**
     * @param {String} description
     */
    setDescription(description) {
        this['description'] = description;
    }
/**
     * @return {String}
     */
    getSummary() {
        return this.summary;
    }

    /**
     * @param {String} summary
     */
    setSummary(summary) {
        this['summary'] = summary;
    }
/**
     * @return {String}
     */
    getType() {
        return this.type;
    }

    /**
     * @param {String} type
     */
    setType(type) {
        this['type'] = type;
    }

}

/**
 * @member {Object} configuration
 */
V1ServiceProviderSpec.prototype['configuration'] = undefined;

/**
 * @member {Array.<module:model/V1ConfigurationFromSource>} configurationFrom
 */
V1ServiceProviderSpec.prototype['configurationFrom'] = undefined;

/**
 * @member {String} description
 */
V1ServiceProviderSpec.prototype['description'] = undefined;

/**
 * @member {String} summary
 */
V1ServiceProviderSpec.prototype['summary'] = undefined;

/**
 * @member {String} type
 */
V1ServiceProviderSpec.prototype['type'] = undefined;






export default V1ServiceProviderSpec;

