/**
 * Appvia Kore API
 * Kore API provides the frontend API for the Appvia Kore (kore.appvia.io)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@appvia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ValidationFieldError from './ValidationFieldError';

/**
 * The ValidationError model module.
 * @module model/ValidationError
 * @version 0.0.1
 */
class ValidationError {
    /**
     * Constructs a new <code>ValidationError</code>.
     * @alias module:model/ValidationError
     * @param code {Number} 
     * @param fieldErrors {Array.<module:model/ValidationFieldError>} 
     * @param message {String} 
     */
    constructor(code, fieldErrors, message) { 
        
        ValidationError.initialize(this, code, fieldErrors, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, fieldErrors, message) { 
        obj['code'] = code;
        obj['fieldErrors'] = fieldErrors;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>ValidationError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidationError} obj Optional instance to populate.
     * @return {module:model/ValidationError} The populated <code>ValidationError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationError();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('fieldErrors')) {
                obj['fieldErrors'] = ApiClient.convertToType(data['fieldErrors'], [ValidationFieldError]);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {Number}
     */
    getCode() {
        return this.code;
    }

    /**
     * @param {Number} code
     */
    setCode(code) {
        this['code'] = code;
    }
/**
     * @return {Array.<module:model/ValidationFieldError>}
     */
    getFieldErrors() {
        return this.fieldErrors;
    }

    /**
     * @param {Array.<module:model/ValidationFieldError>} fieldErrors
     */
    setFieldErrors(fieldErrors) {
        this['fieldErrors'] = fieldErrors;
    }
/**
     * @return {String}
     */
    getMessage() {
        return this.message;
    }

    /**
     * @param {String} message
     */
    setMessage(message) {
        this['message'] = message;
    }

}

/**
 * @member {Number} code
 */
ValidationError.prototype['code'] = undefined;

/**
 * @member {Array.<module:model/ValidationFieldError>} fieldErrors
 */
ValidationError.prototype['fieldErrors'] = undefined;

/**
 * @member {String} message
 */
ValidationError.prototype['message'] = undefined;






export default ValidationError;

