// +build !ignore_autogenerated

/**
 * Copyright 2020 Appvia Ltd <info@appvia.io>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityOverview) DeepCopyInto(out *SecurityOverview) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityOverview.
func (in *SecurityOverview) DeepCopy() *SecurityOverview {
	if in == nil {
		return nil
	}
	out := new(SecurityOverview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityOverview) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityOverviewSpec) DeepCopyInto(out *SecurityOverviewSpec) {
	*out = *in
	if in.OpenIssueCounts != nil {
		in, out := &in.OpenIssueCounts, &out.OpenIssueCounts
		*out = make(map[RuleStatus]uint64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]SecurityResourceOverview, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityOverviewSpec.
func (in *SecurityOverviewSpec) DeepCopy() *SecurityOverviewSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityOverviewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityResourceOverview) DeepCopyInto(out *SecurityResourceOverview) {
	*out = *in
	out.Resource = in.Resource
	in.LastChecked.DeepCopyInto(&out.LastChecked)
	if in.OpenIssueCounts != nil {
		in, out := &in.OpenIssueCounts, &out.OpenIssueCounts
		*out = make(map[RuleStatus]uint64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityResourceOverview.
func (in *SecurityResourceOverview) DeepCopy() *SecurityResourceOverview {
	if in == nil {
		return nil
	}
	out := new(SecurityResourceOverview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRule) DeepCopyInto(out *SecurityRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRule.
func (in *SecurityRule) DeepCopy() *SecurityRule {
	if in == nil {
		return nil
	}
	out := new(SecurityRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRuleList) DeepCopyInto(out *SecurityRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRuleList.
func (in *SecurityRuleList) DeepCopy() *SecurityRuleList {
	if in == nil {
		return nil
	}
	out := new(SecurityRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRuleSpec) DeepCopyInto(out *SecurityRuleSpec) {
	*out = *in
	if in.AppliesTo != nil {
		in, out := &in.AppliesTo, &out.AppliesTo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRuleSpec.
func (in *SecurityRuleSpec) DeepCopy() *SecurityRuleSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityScanResult) DeepCopyInto(out *SecurityScanResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityScanResult.
func (in *SecurityScanResult) DeepCopy() *SecurityScanResult {
	if in == nil {
		return nil
	}
	out := new(SecurityScanResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityScanResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityScanResultList) DeepCopyInto(out *SecurityScanResultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityScanResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityScanResultList.
func (in *SecurityScanResultList) DeepCopy() *SecurityScanResultList {
	if in == nil {
		return nil
	}
	out := new(SecurityScanResultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityScanResultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityScanResultSpec) DeepCopyInto(out *SecurityScanResultSpec) {
	*out = *in
	out.Resource = in.Resource
	in.CheckedAt.DeepCopyInto(&out.CheckedAt)
	in.ArchivedAt.DeepCopyInto(&out.ArchivedAt)
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]SecurityScanRuleResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityScanResultSpec.
func (in *SecurityScanResultSpec) DeepCopy() *SecurityScanResultSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityScanResultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityScanRuleResult) DeepCopyInto(out *SecurityScanRuleResult) {
	*out = *in
	in.CheckedAt.DeepCopyInto(&out.CheckedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityScanRuleResult.
func (in *SecurityScanRuleResult) DeepCopy() *SecurityScanRuleResult {
	if in == nil {
		return nil
	}
	out := new(SecurityScanRuleResult)
	in.DeepCopyInto(out)
	return out
}
